### ISSUE TITLE
Testing monochromatic images on your code

### ISSUE THREAD

**Issue by iucurmak** [fab-jul/imgcomp-cvpr#19]
How can i apply to testing your code for monochromatic images. Is it possible? Or what i need to change from your code? Could you please let me know?

**Comment by fab-jul** [comment]
The network is not trained for monochromatic images. In theory, you can feed it a monochromatic image by repeating it across the channel dimension. Meaning if you have a monochromatic image `x` with shape `(H, W, 1)`, you can do `tf.repeat` it into `(H, W, 3)`. The resulting bitrate will however be suboptimal, since the network is not trained to leverage the redundancies now.

**Comment by fab-jul** [comment]
In theory you could train a new network however, where the input and output is `(H,W,1)` dimensional instead.

**Comment by iucurmak** [comment]
Thank you for informing me. Which files i need to rearrange if i train the code for monochromatic images? And also which files need rearrangement for testing code?

**Comment by fab-jul** [comment]
Probably requires quite some changes -- essentially everywhere where the code assumes a channel dimension of 3. Some locations:

- In [`inputpipeline.py`](https://github.com/fab-jul/imgcomp-cvpr/blob/master/code/inputpipeline.py) the `images_decoded` and `_preprocess` functions
- In [`autoencoder.py`](https://github.com/fab-jul/imgcomp-cvpr/blob/f03ce0bfa846f7ba1bf9b7ba415b082efe5c192c/code/autoencoder.py) the `get_mean_var` function (must calculate new mean/variance or just use average of the means/variances there)

Starting from the changes in `inputpipeline.py`, you can probably run it and follow the errors.

**Comment by iucurmak** [comment]
Appreciate for your help. Have great day.

**Comment by fab-jul** [comment]
Let me know if you manage to train a model for monochromatic, would be interesting!
