### ISSUE TITLE
Saving quantized images.

### ISSUE THREAD

**Issue by nit96kaus** [fab-jul/imgcomp-cvpr#9]
If I save the quantized volume after the quantizer, the numpy file is larger in size than the original image. How to save the compressed form so that it takes lesser memory than the original image ?

**Comment by fab-jul** [comment]
Please have a look at [this section in the README](https://github.com/fab-jul/imgcomp-cvpr#encoding-to-bitstream) and especially [the code here](https://github.com/fab-jul/imgcomp-cvpr/blob/master/code/bit_counter.py), where the image gets written to a temporary file at `fout_p`. If you use the numpy directly, you need many more bits, e.g., if you use `uint8`, every symbol takes 8 bits instead of H(symbol) bits.

**Comment by nit96kaus** [comment]
Thanks a lot.
